# docker compose up -d bouwt en start de statische site lokaal in een nginx-container.
services:
  stentijhuis:
    build:
      context: .
      dockerfile: Dockerfile

    # Poort 8080 op de host, poort 80 in de container (standaard HTTP)
    ports:
      - "8080:80"

    container_name: stentijhuis.nl

    # Herstart automatisch bij crashen of na rebooten van de host
    restart: always
